{
  "openapi": "3.1.0",
  "info": {
    "title": "net2phone webhooks",
    "description": "<h2>Introduction</h2>The net2phone webhooks give you the ability to receive a structured payload of data at the URL of your choice when certain events occur. For example, you can use the webhooks to notify your CRM application that a call has been completed or notify your messaging application that a call has been parked or unparked<br /><br /><h2>Getting started</h2>Log into https://app.net2phone.com and go to Settings / API, click on the ‘Webhook’ tab, and click on ‘Add Webhook’, follow the on screen directions to set up the webhook.",
    "version": "1.0"
  },
  "servers": [
    {
      "url": ""
    }
  ],
  "tags": [],
  "paths": {},
  "components": {
    "schemas": {
      "call_answered": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_answered.v1.yaml"
      },
      "call_blind_transfer": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_blind_transfer.v1.yaml"
      },
      "call_blocked": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_blocked.v1.yaml"
      },
      "call_busy": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_busy.v1.yaml"
      },
      "call_completed": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_completed.v1.yaml"
      },
      "call_consultative_transfer": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_consultative_transfer.v1.yaml"
      },
      "call_forward": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_forward.v1.yaml"
      },
      "call_hold": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_hold.v1.yaml"
      },
      "call_missed": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_missed.v1.yaml"
      },
      "call_park": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_park.v1.yaml"
      },
      "call_pickup": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_pickup.v1.yaml"
      },
      "call_recorded": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_recorded.v1.yaml"
      },
      "call_recording_failed": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_recording_failed.v1.yaml"
      },
      "call_resume": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_resume.v1.yaml"
      },
      "call_rg_queue_completed": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_rg_queue_completed.v1.yaml"
      },
      "call_rg_queue_entered": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_rg_queue_entered.v1.yaml"
      },
      "call_rg_queue_tier": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_rg_queue_tier.v1.yaml"
      },
      "call_ringing": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_ringing.v1.yaml"
      },
      "call_unpark": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_unpark.v1.yaml"
      },
      "emergency_call": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/emergency_call.v1.yaml"
      },
      "message_received": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/message_received.v1.yaml"
      },
      "voicemail_missed": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/voicemail_missed.v1.yaml"
      },
      "voicemail_notify": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/voicemail_notify.v1.yaml"
      },
      "voicemail_received": {
        "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/voicemail_received.v1.yaml"
      }
    }
  },
  "webhooks": {
    "call_answered": {
      "summary": "Call answered",
      "description": "This event is triggered when a Team Member answers an incoming call or when an outgoing call is answered by the dialed destination number",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_answered.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_answered",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "inbound",
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal"
                    }
                  },
                  "click2call example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_answered",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "inbound",
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "click2call",
                      "click_to_call_info": {
                        "c2c_api_request_id": "932b34fc-fb110c6bc859c542",
                        "c2c_client_id": "n2p-api"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "call_blind_transfer": {
      "summary": "Call blind transfer",
      "description": "This event is issued when a Team Member transfers a call via  blind (cold) transfer",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_blind_transfer.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_blind_transfer",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "inbound",
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "call_blocked": {
      "summary": "Call blocked",
      "description": "This event is triggered when an incoming call is blocked.<br/>\nIf the number is blocked at the account level only the `user.account_id` field is present - see examples.",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_blocked.v1.yaml"
                },
                "examples": {
                  "user level blocked example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_blocked",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "inbound",
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal"
                    }
                  },
                  "account level blocked example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_blocked",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "inbound",
                      "user": {
                        "account_id": 67890
                      },
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "call_busy": {
      "summary": "Call busy",
      "description": "The event is triggered when an outbound call receives a 4xx or 5xx error response to the INVITE indicating the call failed for some reason",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_busy.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_busy",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "outbound",
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "call_completed": {
      "summary": "Call completed",
      "description": "Event is triggered when a call is successfully completed. This event will trigger for both inbound and outbound calls.",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_completed.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_completed",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "outbound",
                      "duration": 36,
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal"
                    }
                  },
                  "click2call example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_completed",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "outbound",
                      "duration": 36,
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "click2call",
                      "click_to_call_info": {
                        "c2c_api_request_id": "932b34fc-fb110c6bc859c542",
                        "c2c_client_id": "n2p-api"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "call_consultative_transfer": {
      "summary": "Call consultative_transfer",
      "description": "This event is issued when a Team Member transfers a call via  consultative (warm) transfer",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_consultative_transfer.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_consultative_transfer",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "outbound",
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "reason": "transferer",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "call_forward": {
      "summary": "Call forward",
      "description": "This event is triggered when a Team Member forwards a call",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_forward.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_forward",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "inbound",
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "forward_number": 19739212598,
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "call_hold": {
      "summary": "Call hold",
      "description": "This event is triggered when a Team Member puts a call on hold",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_hold.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_hold",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "inbound",
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "reason": "holder",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "call_missed": {
      "summary": "Call missed",
      "description": "This event is triggered when an incoming call isn’t answered by any phone in your net2phone account.\nThe reason field indicates the reason the call was missed and can be `user_did_not_answer` if the Team Member didn’t answer, `user_rejected_call` if the Team Member actively rejected the call, or `user_not_logged_in` if calling another net2phone user who is not logged in",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_missed.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_missed",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "outbound",
                      "duration": 0,
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "reason": "user_did_not_answer",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal"
                    }
                  },
                  "click2call example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_missed",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "outbound",
                      "duration": 0,
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "reason": "user_did_not_answer",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "click2call",
                      "click_to_call_info": {
                        "c2c_api_request_id": "932b34fc-fb110c6bc859c542",
                        "c2c_client_id": "n2p-api"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "call_park": {
      "summary": "Call park",
      "description": "This event is triggered when a Team Member parks a call",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_park.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_park",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "outbound",
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal",
                      "slot": 1
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "call_pickup": {
      "summary": "Call pickup",
      "description": "This notification is triggered when a Team Member uses the Pick Up feature (*21) to answer a call ringing on another Team Members extension",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_pickup.v1.yaml"
                },
                "examples": {
                  "user-example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_pickup",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "outbound",
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "pickup_event_info": {
                        "id": 98765,
                        "name": "Peter Parker",
                        "extension": 4321
                      },
                      "call_source": "normal"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "call_recorded": {
      "summary": "Call recorded",
      "description": "This event is triggered when an inbound or outbound call has been successfully recorded.",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_recorded.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_recorded",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "inbound",
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal",
                      "audio_message_id": 123456789
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "call_recording_failed": {
      "summary": "Call recording failed",
      "description": "This event is triggered when a call fails to record",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_recording_failed.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_recording_failed",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "inbound",
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "reason": "maxCallRecordings",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "call_resume": {
      "summary": "Call resume",
      "description": "This event is triggered when a Team Member resumes a call",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_resume.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_resume",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "inbound",
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "reason": "resumer",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "call_rg_queue_completed": {
      "summary": "Call ring group queue completed",
      "description": "The event is issued when a call in a RG completes by either being answered in a Tier or the caller hangs up.",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_rg_queue_completed.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_rg_queue_completed",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "inbound",
                      "user": {
                        "account_id": 67890
                      },
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "call_rg_queue_entered": {
      "summary": "Call ring group queue entered",
      "description": "The event is issued when a call enters a RG with call queue enabled",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_rg_queue_entered.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_rg_queue_entered",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "inbound",
                      "user": {
                        "account_id": 67890
                      },
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "call_rg_queue_tier": {
      "summary": "Call ring group queue sent to tier",
      "description": "The event is issued when a call waiting in a RG with call queue enabled enters a Tier which results in calls being sent to TM in that Tier.",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_rg_queue_tier.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_rg_queue_tier",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "inbound",
                      "user": {
                        "account_id": 67890
                      },
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "call_ringing": {
      "summary": "Call ringing",
      "description": "This event is triggered when a call is ringing. This event will trigger for both inbound and outbound calls and is typically followed by by a `call_answered` or `call_missed` event",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_ringing.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_ringing",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "inbound",
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal"
                    }
                  },
                  "click2call example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_ringing",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "inbound",
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "click2call",
                      "click_to_call_info": {
                        "c2c_api_request_id": "932b34fc-fb110c6bc859c542",
                        "c2c_client_id": "n2p-api"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "call_unpark": {
      "summary": "Call unpark",
      "description": "This event is triggered when a Team Member unparks a call. NOTE The team member that unparks a call will also get a call_answered event",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/call_unpark.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "call_unpark",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "outbound",
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal",
                      "slot": 1
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "emergency_call": {
      "summary": "Emergency call",
      "description": "This event is triggered when a call is placed to an emergency serivce",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/emergency_call.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "emergency_call",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "inbound",
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "originating_number": "+19734381000",
                      "dialed_number": 911,
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "message_received": {
      "summary": "Message Received",
      "description": "This event is triggered when a Team Member or Account receives a message",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/message_received.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "message_received",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "Sergey Belavsky",
                      "messenger_info": {
                        "message_id": "83da998362ddd2e82b1db315",
                        "conversation_id": "2c83d34c0e9ec63a2342d98a",
                        "type": "SMS",
                        "originated": 19734381000,
                        "terminated": 19739217310,
                        "origin": "external",
                        "target": "user",
                        "content": "hello world",
                        "from_user_id": "ef9d4caed46726d4d57c6460"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "voicemail_missed": {
      "summary": "Voicemail missed",
      "description": "This event is triggered when an incoming call is sent to a Team Member’s voicemail but the caller doesn’t leave a voicemail.  A common scenario for this would be the case where the callers hangs up before leaving a voicemail.<br/>\nThe reason field describes the reason for the caller didn’t leave a voicemail can can be either `caller_hungup` if the caller disconnected before recording a message or `vm_disabled` if the Team Member’s VM account was disabled at the time",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/voicemail_missed.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "voicemail_missed",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "inbound",
                      "duration": 12,
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "reason": "caller_hungup",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal"
                    }
                  },
                  "click2call example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "voicemail_missed",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "inbound",
                      "duration": 12,
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "reason": "caller_hungup",
                      "originating_number": "+19734381000",
                      "dialed_number": "+19739217310",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "click2call",
                      "click_to_call_info": {
                        "c2c_api_request_id": "932b34fc-fb110c6bc859c542",
                        "c2c_client_id": "n2p-api"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "voicemail_notify": {
      "summary": "Voicemail notify",
      "description": "This event is triggered when an incoming call is sent to a Team Member’s voicemail but the caller doesn’t leave a voicemail.  A common scenario for this would be the case where the callers hangs up before leaving a voicemail.<br/>\nThe reason field describes the reason for the caller didn’t leave a voicemail can can be either `caller_hungup` if the caller disconnected before recording a message or `vm_disabled` if the Team Member’s VM account was disabled at the time",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/voicemail_notify.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "voicemail_notify",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "inbound",
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "voicemail": true,
                      "originating_number": "+19734381000",
                      "dialed_number": "*95",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "voicemail_received": {
      "summary": "Voicemail received",
      "description": "A voicemail was left for a net2phone user. This event will trigger when an incoming (only) call is not answered by any phone in your net2phone account and a voicemail is recorded.",
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/coretech/n2p-i2-docs/dev/models/webhooks/voicemail_received.v1.yaml"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "event": "voicemail_received",
                      "timestamp": "2019-08-24T14:15:22.000Z",
                      "direction": "inbound",
                      "duration": 12,
                      "user": {
                        "id": 12345,
                        "name": "James T Kirk",
                        "account_id": 67890
                      },
                      "user_name": "James T Kirk",
                      "originating_number": "+19734381000",
                      "dialed_number": "*95",
                      "call_leg_id": "c461419d34b1e66fb7ec5e15e0dc5202",
                      "call_id": "818787cc58e3043c4b4721ed0c157735",
                      "call_source": "normal",
                      "audio_message_id": 123456789,
                      "voicemail": true
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}