{
  "openapi": "3.1.0",
  "info": {
    "title": "net2phone integrate apis",
    "description": "<h2>Introduction</h2>This is going to be a really cool description",
    "version": "1.8"
  },
  "servers": [
    {
      "url": ""
    }
  ],
  "tags": [
    {
      "name": "Devices",
      "description": "Lists of registered devices"
    },
    {
      "name": "Number Portability",
      "description": "Check if a given phone number is portable to Versature"
    },
    {
      "name": "Presence",
      "description": "Presence of users for a given domain"
    },
    {
      "name": "Recordings",
      "description": "Get the recordings for a CDR"
    },
    {
      "name": "Users",
      "description": "Get a list of the Users for your company or details aobut a specific user."
    },
    {
      "name": "Voicemails",
      "description": "Get information about Voicemails for users in a domain"
    },
    {
      "name": "Webhooks",
      "description": "Subscribe and receive webhook updates for the events you are interested in. Provide a URI which can receive POST requests. When updates occur your endpoint will then be notified. (All notifications requests contain JSON.)"
    }
  ],
  "paths": {
    "/devices/users/": {
      "get": {
        "summary": "Get a list of user devices in an account.",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/devices"
                },
                "examples": {
                  "example": {
                    "$ref": "#/components/examples/devices"
                  }
                }
              }
            },
            "description": "Success"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "422": {
            "$ref": "#/components/responses/InvalidVersion"
          },
          "429": {
            "$ref": "#/components/responses/RateLimitExceeded"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        },
        "tags": [
          "Devices"
        ],
        "parameters": [
          {
            "$ref": "#/components/headers/Accept"
          }
        ]
      }
    },
    "/devices/users/current/": {
      "get": {
        "summary": "Get a list of devices for the authenticated user.",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/devices"
                },
                "examples": {
                  "example": {
                    "$ref": "#/components/examples/devices"
                  }
                }
              }
            },
            "description": "Success"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "422": {
            "$ref": "#/components/responses/InvalidVersion"
          },
          "429": {
            "$ref": "#/components/responses/RateLimitExceeded"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        },
        "tags": [
          "Devices"
        ],
        "parameters": [
          {
            "$ref": "#/components/headers/Accept"
          }
        ]
      }
    },
    "/devices/users/{userId}/": {
      "get": {
        "summary": "Get a list of devices for the specified user.",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/devices"
                },
                "examples": {
                  "example": {
                    "$ref": "#/components/examples/devices"
                  }
                }
              }
            },
            "description": "Success"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "422": {
            "$ref": "#/components/responses/InvalidVersion"
          },
          "429": {
            "$ref": "#/components/responses/RateLimitExceeded"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        },
        "tags": [
          "Devices"
        ],
        "parameters": [
          {
            "$ref": "#/components/headers/Accept"
          }
        ]
      }
    },
    "/phone_numbers/{phone_number}/portability/": {
      "get": {
        "parameters": [
          {
            "$ref": "#/components/headers/Accept"
          },
          {
            "$ref": "#/components/parameters/phone_number"
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/portability"
                },
                "examples": {
                  "example": {
                    "$ref": "#/components/examples/portability"
                  }
                }
              }
            },
            "description": "Success"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "422": {
            "$ref": "#/components/responses/InvalidVersion"
          },
          "429": {
            "$ref": "#/components/responses/RateLimitExceeded"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        },
        "tags": [
          "Number Portability"
        ]
      }
    },
    "/presence/": {
      "get": {
        "summary": "Get a list of users with their presence on device.",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/presence"
                },
                "examples": {
                  "example": {
                    "$ref": "#/components/examples/presence"
                  }
                }
              }
            },
            "description": "Success"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "422": {
            "$ref": "#/components/responses/InvalidVersion"
          },
          "429": {
            "$ref": "#/components/responses/RateLimitExceeded"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        },
        "tags": [
          "Presence"
        ],
        "parameters": [
          {
            "$ref": "#/components/headers/Accept"
          }
        ]
      }
    },
    "/recordings/{recordingId}": {
      "get": {
        "summary": "Get the recordings for a given call by it's id.",
        "parameters": [
          {
            "$ref": "#/components/headers/Accept"
          },
          {
            "$ref": "#/components/parameters/recordingId"
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/recording"
                },
                "examples": {
                  "example": {
                    "$ref": "#/components/examples/recording"
                  }
                }
              }
            },
            "description": "Success"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "422": {
            "$ref": "#/components/responses/InvalidVersion"
          },
          "429": {
            "$ref": "#/components/responses/RateLimitExceeded"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        },
        "tags": [
          "Recordings"
        ]
      }
    },
    "/users/": {
      "get": {
        "summary": "Get details list of all users of an account",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/user"
                  }
                },
                "examples": {
                  "example": {
                    "$ref": "#/components/examples/users"
                  }
                }
              }
            },
            "description": "Success"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "422": {
            "$ref": "#/components/responses/InvalidVersion"
          },
          "429": {
            "$ref": "#/components/responses/RateLimitExceeded"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        },
        "tags": [
          "Users"
        ],
        "parameters": [
          {
            "$ref": "#/components/headers/Accept"
          }
        ]
      }
    },
    "/users/{userId}/": {
      "get": {
        "summary": "Get the user details. If provided the id will be used to get a specific user. If not specified the authenticated user details will be returned. If you wish to retrieve all users across your domain use the \"all\" argument.",
        "parameters": [
          {
            "$ref": "#/components/headers/Accept"
          },
          {
            "$ref": "#/components/parameters/userId"
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/user"
                },
                "examples": {
                  "example": {
                    "$ref": "#/components/examples/user"
                  }
                }
              }
            },
            "description": "Success"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "422": {
            "$ref": "#/components/responses/InvalidVersion"
          },
          "429": {
            "$ref": "#/components/responses/RateLimitExceeded"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        },
        "tags": [
          "Users"
        ]
      }
    },
    "/users/current/": {
      "get": {
        "summary": "Get the user details for the authenticated user.",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/user"
                },
                "examples": {
                  "example": {
                    "$ref": "#/components/examples/user"
                  }
                }
              }
            },
            "description": "Success"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "422": {
            "$ref": "#/components/responses/InvalidVersion"
          },
          "429": {
            "$ref": "#/components/responses/RateLimitExceeded"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        },
        "tags": [
          "Users"
        ],
        "parameters": [
          {
            "$ref": "#/components/headers/Accept"
          }
        ]
      }
    },
    "/voicemails/users/{userId}/count/": {
      "get": {
        "summary": "Get the voicemail count for a user in a domain.",
        "parameters": [
          {
            "$ref": "#/components/headers/Accept"
          },
          {
            "$ref": "#/components/parameters/userId"
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/voicemail_count"
                },
                "examples": {
                  "example": {
                    "$ref": "#/components/examples/voicemail_count"
                  }
                }
              }
            },
            "description": "Success"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "422": {
            "$ref": "#/components/responses/InvalidVersion"
          },
          "429": {
            "$ref": "#/components/responses/RateLimitExceeded"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        },
        "tags": [
          "Voicemails"
        ]
      }
    },
    "/subscriptions/": {
      "post": {
        "summary": "Creates a webhook subscription for the requested events.\nWhen an event occurs to which you are subscribed a POST request will be set to your post_uri with a JSON body indicating what occurred.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/webhook_settings"
              },
              "examples": {
                "example": {
                  "$ref": "#/components/examples/webhook_settings"
                }
              }
            }
          }
        },
        "responses": {
          "202": {
            "description": "Accepted",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/webhook_subscription"
                },
                "examples": {
                  "example": {
                    "$ref": "#/components/examples/webhook_subscription"
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "422": {
            "$ref": "#/components/responses/InvalidVersion"
          },
          "429": {
            "$ref": "#/components/responses/RateLimitExceeded"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        },
        "tags": [
          "Webhooks"
        ],
        "parameters": [
          {
            "$ref": "#/components/headers/Accept"
          }
        ]
      }
    },
    "/subscriptions/{subscriptionId}/": {
      "delete": {
        "summary": "Delete a webhook subscription with the given id. Updates will no longer be sent the subscription endpoint.\nNote: Users can only delete subscriptions that they created.",
        "parameters": [
          {
            "$ref": "#/components/headers/Accept"
          },
          {
            "$ref": "#/components/parameters/subscriptionId"
          }
        ],
        "responses": {
          "204": {
            "description": "The webhook subscription was deleted successfully."
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "422": {
            "$ref": "#/components/responses/InvalidVersion"
          },
          "429": {
            "$ref": "#/components/responses/RateLimitExceeded"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        },
        "tags": [
          "Webhooks"
        ]
      },
      "get": {
        "summary": "Get the webhook subscription details for the given id. Can be used to verify subscribed events as well the subscription expiry date/time.\nNote: Users can only read subscriptions that they created.",
        "parameters": [
          {
            "$ref": "#/components/headers/Accept"
          },
          {
            "$ref": "#/components/parameters/subscriptionId"
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/webhook_subscription"
                },
                "examples": {
                  "example": {
                    "$ref": "#/components/examples/webhook_subscription"
                  }
                }
              }
            },
            "description": "Success"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "422": {
            "$ref": "#/components/responses/InvalidVersion"
          },
          "429": {
            "$ref": "#/components/responses/RateLimitExceeded"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        },
        "tags": [
          "Webhooks"
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "devices": {
        "title": "Devices list",
        "type": "array",
        "description": "List of devices",
        "uniqueItems": true,
        "items": {
          "type": "object",
          "properties": {
            "aor": {
              "type": "string",
              "description": "The address of record for this device."
            },
            "aor_user": {
              "type": "string",
              "description": "The user portion of the address of record for this device."
            },
            "mac": {
              "type": "string",
              "description": "The mac address of the device."
            },
            "model": {
              "type": "string",
              "description": "The model of the device"
            },
            "registration_time": {
              "type": "string",
              "description": "The time when the device was registered. `YYYY-MM-DDTHH:MM:SS+00:00`",
              "format": "date-time"
            }
          }
        }
      },
      "portability": {
        "title": "Portability",
        "type": "object",
        "description": "Phone number portablility response",
        "properties": {
          "portable": {
            "type": "boolean",
            "default": true,
            "description": "Is the provided phone number portable."
          }
        }
      },
      "presence": {
        "title": "User Device Presence",
        "type": "object",
        "description": "User device presence",
        "properties": {
          "user": {
            "type": "string",
            "description": "The user's extension"
          },
          "first_name": {
            "type": "string",
            "description": "The first name of the user"
          },
          "last_name": {
            "type": "string",
            "description": "The last name of the user"
          },
          "email": {
            "type": "string",
            "description": "The email address of the user"
          },
          "domain": {
            "type": "string",
            "description": "The domain for the user"
          },
          "presence": {
            "type": "string",
            "description": "The presence status of the user",
            "enum": [
              "open"
            ]
          }
        }
      },
      "recording": {
        "title": "Recording",
        "type": "object",
        "description": "Details of the recording",
        "properties": {
          "status": {
            "type": "string",
            "description": "The status of the recording. `Available` when it is ready to go. `Processing` when still being processed and `No Recording` when it has been deleted or is not available",
            "enum": [
              "available",
              "processing",
              "no recording"
            ]
          },
          "url": {
            "type": "string",
            "format": "uri",
            "description": "The path to the recorded file"
          },
          "duration": {
            "type": "integer",
            "format": "int32",
            "description": "The length of the recording in seconds"
          }
        }
      },
      "user": {
        "title": "User Details",
        "type": "object",
        "description": "Details of the user",
        "required": [
          "username",
          "user",
          "first_name",
          "last_name",
          "email",
          "time_zone",
          "scope"
        ],
        "properties": {
          "username": {
            "type": "string",
            "description": "The user identifier"
          },
          "user": {
            "type": "string",
            "description": "The user's extension"
          },
          "first_name": {
            "type": "string",
            "description": "The first name of the user"
          },
          "last_name": {
            "type": "string",
            "description": "The last name of the user"
          },
          "email": {
            "type": "string",
            "description": "The email address of the user"
          },
          "domain": {
            "type": "string",
            "description": "The domain for the user"
          },
          "time_zone": {
            "type": "string",
            "description": "The time zone this user resides in"
          },
          "scope": {
            "type": "string",
            "description": "The role of this user",
            "enum": [
              "Basic User",
              "Office Manager",
              "Call Center Supervisor",
              "Call Center User"
            ]
          }
        }
      },
      "voicemail_count": {
        "title": "Voicemail Count",
        "type": "object",
        "description": "Count of all voicemails for a given user",
        "properties": {
          "new": {
            "type": "integer",
            "format": "int32",
            "description": "The total count of new voicemails for the specified user"
          },
          "saved": {
            "type": "integer",
            "format": "int32",
            "description": "The total count of saved voicemails for the specified user"
          }
        }
      },
      "webhook_settings": {
        "required": [
          "post_uri"
        ],
        "type": "object",
        "properties": {
          "post_uri": {
            "type": "string",
            "description": "The endpoint which is notified when an event occurs.",
            "format": "uri"
          },
          "expires_in": {
            "type": "integer",
            "format": "int32",
            "description": "The number of seconds until the webhook subscription expires",
            "default": 7200,
            "maximum": 604800
          },
          "calls": {
            "type": "boolean",
            "description": "Subscribe to call events",
            "default": false
          },
          "cdrs": {
            "type": "boolean",
            "default": false,
            "description": "Subscribe to CDR events"
          },
          "recordings": {
            "type": "boolean",
            "description": "Subscribe to recording events",
            "default": false
          },
          "user": {
            "type": "string",
            "description": "One or more users to subscribe to. Omit to subscribe to all users webhooks.\nAppend multiple times to subscribe to multiple users.",
            "default": "*"
          }
        }
      },
      "webhook_subscription": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "required": true,
            "description": "The unique id of this subscription",
            "format": "int32"
          },
          "post_uri": {
            "type": "string",
            "description": "The endpoint which is notified when an event occurs.",
            "format": "uri"
          },
          "events": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "properties": {
                "type": {
                  "type": "string",
                  "required": true,
                  "enum": [
                    "calls",
                    "cdrs",
                    "recordings"
                  ]
                },
                "user": {
                  "type": "string",
                  "required": true,
                  "default": "*"
                }
              }
            }
          },
          "enabled": {
            "type": "boolean",
            "description": "Indicates if subscription is enabled"
          }
        }
      }
    },
    "responses": {
      "Unauthorized": {
        "description": "Unauthorized",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer",
                  "format": "int32",
                  "required": true,
                  "enum": [
                    401
                  ]
                },
                "message": {
                  "type": "string",
                  "required": true,
                  "enum": [
                    "Invalid Vendor"
                  ]
                }
              }
            },
            "example": {
              "status": 401,
              "message": "Invalid Vendor"
            }
          }
        }
      },
      "Forbidden": {
        "description": "Forbidden",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer",
                  "format": "int32",
                  "required": true,
                  "enum": [
                    403
                  ]
                },
                "message": {
                  "type": "string",
                  "required": true,
                  "enum": [
                    "Access Forbidden, you do not have the correct permissions."
                  ]
                }
              }
            },
            "example": {
              "status": 403,
              "message": "Access Forbidden, you do not have the correct permissions."
            }
          }
        }
      },
      "NotFound": {
        "description": "Not Found",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer",
                  "format": "int32",
                  "required": true,
                  "enum": [
                    404
                  ]
                },
                "message": {
                  "type": "string",
                  "required": true,
                  "enum": [
                    "Resource does not exist."
                  ]
                }
              }
            },
            "example": {
              "status": 404,
              "message": "Resource does not exist."
            }
          }
        }
      },
      "InvalidVersion": {
        "description": "Invalid Version",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer",
                  "format": "int32",
                  "required": true,
                  "enum": [
                    422
                  ]
                },
                "message": {
                  "type": "string",
                  "required": true,
                  "enum": [
                    "An invalid version number was provided."
                  ]
                }
              }
            },
            "example": {
              "status": 422,
              "message": "An invalid version number was provided."
            }
          }
        }
      },
      "RateLimitExceeded": {
        "description": "Rate Limit Exceeded",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer",
                  "format": "int32",
                  "required": true,
                  "enum": [
                    429
                  ]
                },
                "message": {
                  "type": "string",
                  "required": true,
                  "enum": [
                    ""
                  ]
                }
              }
            },
            "example": {
              "status": 429,
              "message": ""
            }
          }
        }
      },
      "InternalServerError": {
        "description": "Internal Server Error",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer",
                  "format": "int32",
                  "required": true,
                  "enum": [
                    500
                  ]
                },
                "message": {
                  "type": "string",
                  "required": true,
                  "enum": [
                    "An error occurred while marshalling the response."
                  ]
                }
              }
            },
            "example": {
              "status": 500,
              "message": "An error occurred while marshalling the response."
            }
          }
        }
      }
    },
    "parameters": {
      "callId": {
        "name": "callId",
        "in": "path",
        "description": "The ID of the call",
        "required": true,
        "schema": {
          "type": "string",
          "nullable": true
        }
      },
      "recordingId": {
        "name": "recordingId",
        "in": "path",
        "description": "Id of the recording",
        "required": true,
        "schema": {
          "type": "integer",
          "format": "int32",
          "nullable": true
        }
      },
      "subscriptionId": {
        "name": "subscriptionId",
        "in": "path",
        "description": "The ID of the subscription",
        "required": true,
        "schema": {
          "type": "integer",
          "format": "int32"
        }
      },
      "userId": {
        "name": "userId",
        "in": "path",
        "description": "Id of the user",
        "required": true,
        "schema": {
          "type": "integer",
          "format": "int32",
          "nullable": true
        }
      },
      "phone_number": {
        "name": "phone_number",
        "in": "path",
        "description": "The phone number to verify. E164 format is ideal but a best effort will be made to format the check the number provided.",
        "required": true,
        "schema": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "headers": {
      "Accept": {
        "name": "Accept",
        "required": true,
        "in": "header",
        "description": "The media type and version which is acceptable for the response",
        "schema": {
          "type": "string",
          "enum": [
            "application/vnd.integrate.v1.1.0+json",
            "application/vnd.integrate.v1.2.0+json",
            "application/vnd.integrate.v1.3.0+json",
            "application/vnd.integrate.v1.4.0+json",
            "application/vnd.integrate.v1.5.0+json",
            "application/vnd.integrate.v1.6.0+json",
            "application/vnd.integrate.v1.7.0+json",
            "application/vnd.integrate.v1.8.0+json"
          ]
        },
        "examples": {
          "latest": {
            "value": "application/vnd.integrate.v1.8.0+json"
          }
        }
      }
    },
    "examples": {
      "devices": {
        "value": [
          {
            "aor": "sip:100@yourdomain.com",
            "aor_user": "100",
            "mac": "1004c84c49ca",
            "model": "Polycom 550",
            "registration_time": "2017-05-23T14:59:59.000Z"
          }
        ]
      },
      "portability": {
        "value": {
          "portable": true
        }
      },
      "presence": {
        "value": {
          "user": "100",
          "first_name": "Smith",
          "last_name": "John",
          "email": "noreply@yourcompany.com",
          "domain": "yourcompany.com",
          "presence": "open"
        }
      },
      "recording": {
        "value": {
          "status": "available",
          "url": "https://example.com",
          "duration": 54
        }
      },
      "user": {
        "value": {
          "username": "110@example.com",
          "user": "100",
          "domain": "example.com",
          "last_name": "Smith",
          "first_name": "John",
          "email": "noreply@versature.com",
          "time_zone": "Canada/Eastern",
          "scope": "Office Manager"
        }
      },
      "users": {
        "value": [
          {
            "username": "110@example.com",
            "user": "100",
            "domain": "example.com",
            "last_name": "Smith",
            "first_name": "John",
            "email": "noreply@versature.com",
            "time_zone": "US/Pacific",
            "scope": "Basic User"
          },
          {
            "username": "220@example.com",
            "user": "220",
            "domain": "example.com",
            "last_name": "Brown",
            "first_name": "Jane",
            "email": "yesreply@versature.com",
            "time_zone": "US/Eastern",
            "scope": "Office Manager"
          }
        ]
      },
      "voicemail_count": {
        "value": {
          "new": 2,
          "saved": 3
        }
      },
      "webhook_settings": {
        "value": {
          "post_uri": "https://mydomain.com/webhooks",
          "expires_in": 604800,
          "calls": false,
          "cdrs": false,
          "recordings": true,
          "user": "*"
        }
      },
      "webhook_subscription": {
        "value": {
          "id": 12345,
          "post_uri": "https://mydomain.com/webhooks",
          "expires": "2021-04-29T11:45:11.110000",
          "events": [
            {
              "type": "cdrs",
              "user": "*"
            },
            {
              "type": "recordings",
              "user": "201"
            }
          ]
        }
      }
    }
  },
  "webhooks": {}
}